FROM python:3.12-slim

WORKDIR /app

# Установка системных зависимостей, если нужны (например, для psycopg2 или других)
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
    && apt-get clean \
    && apt-get install -y iputils-ping \
    && rm -rf /var/lib/apt/lists/*

# Установка зависимостей
COPY requirements.backend.txt .
RUN pip install --no-cache-dir -r requirements.backend.txt

# Копируем исходники
COPY . .

